services:
  keycloak:
    build:
      context: ./docker/key-cloak
      dockerfile: Dockerfile
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_DB: dev-file 
    networks:
      - posteapp_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poste_backend
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb+srv://Giorgia7:100602@servizi.pjgbb1q.mongodb.net/"
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: PosteApp
      KEYCLOAK_CLIENT: poste-frontend
      NODE_ENV: production
    networks:
      - posteapp_network
    depends_on:
      - keycloak

networks:
  posteapp_network:
    driver: bridge
